### ISSUE TITLE
KnightHotfix输出路径问题

### ISSUE THREAD

**Issue by JansonC** [winddyhe/knight#2]
你好，请问为什么KnightHotfix这个类库的输出路径是到\knight-client\Library\Temp\Libs，而不是直接输出到\knight-client\Assets\Game\GameAsset\Hotfix\Libs里呢，我想这两个应该是同样的吧(ㆀ˘･з･˘)

**Comment by winddyhe** [comment]
输出到\knight-client\Library\Temp\Libs是build生成的DLL，然后同时会将生成的这个DLL复制到\knight-client\Assets\Game\GameAsset\Hotfix\Libs这个路径下并重命名它的后缀。这样子做的目的是能够直接用\knight-client\Assets\Game\GameAsset\Hotfix\Libs这个路径下的bytes文件打assetbundle包，同时也避免了主工程发生一次重新编译行为。
