### ISSUE TITLE
我该如何利用该框架构建一个新的游戏

### ISSUE THREAD

**Issue by JansonC** [winddyhe/knight#3]
Hello，我又来提问啦ヾ(･ω･`｡)。
我现在想用knight框架重新开始制作一款游戏的话，我应该从哪里开始，以及有什么注意的地方
(^・ω・^ )( ^・ω・^)(^・ω・^ )( ^・ω・^)

**Comment by winddyhe** [comment]
你可以加我qq讨论下，532815352
