### ISSUE TITLE
同步加载assetbundle

### ISSUE THREAD

**Issue by ZeroKill1024** [winddyhe/knight#4]
你好，我在一个自定义加载回调里加载assetbundle的时候，使用同步的方式调用knight的LoadAsset，直接导致unity 2017编辑器卡死，看unity编辑器的日志就停在了LoadAsset里面，不知道是不是Wait的方式同步调用异步方法导致的。或者knight会提供同步加载接口不呢？

**Comment by winddyhe** [comment]
你使用的是哪一个分支呢？目前只有master分支有同步加载的代码。以前的版本全部都是使用的异步加载的，不能采用同步的方式调用LoadAsset。

**Comment by ZeroKill1024** [comment]
哦，用的release版本，knight 1.0.0b1，我看了下master的代码，找到同步接口了，谢谢了。

**Comment by winddyhe** [comment]
建议你用unity2017.x-unity2018.2.x这个分支版本，这个分支会比release的版本要更加完善一些。
