### ISSUE TITLE
pc 正常 android真机错误 Can not find assetbundle: -- game/hotfix/libs.ab

### ISSUE THREAD

**Issue by fjmygame** [winddyhe/knight#5]
Can not find assetbundle: -- game/hotfix/libs.ab

**Comment by winddyhe** [comment]
Android出版本的时候需要Build Assetbundle，然后将Build的Assetbundle 同步到StreamingAssets下去，这两个命令在Tools/Assetbundle/菜单里面有。

**Comment by winddyhe** [comment]
如果还有问题的话，可以加我们的QQ群来讨论下。

**Comment by fjmygame** [comment]
直接拷备可以
